# Copyright 2023 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

name: Build AMI With Packer Workflow

on:
  push:
    # tags: ["v[0-9].[0-9]+.[0-9]+"]

env:
  PACKER_LOG: 1
  RELEASE_VERSION: v0.4.0

jobs:
  build-ami-with-packer:
    name: Build ami with packer job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code into the directory
        uses: actions/checkout@v3

# get latest tag
#       - name: Set env
#         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Environment version target
        run: |
          echo ${{ env.RELEASE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AMI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_AMI_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./tools/cloud/aws/packer/build_aws_ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate -var \"github_pat=${{ secrets.ONLY_DEFRADB_REPO_CI_PAT }}\" -var \"commit=${{ env.RELEASE_VERSION }}\" ./tools/cloud/aws/packer/build_aws_ami.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build -var \"github_pat=${{ secrets.ONLY_DEFRADB_REPO_CI_PAT }}\" -var \"commit=${{ env.RELEASE_VERSION }}\" ./tools/cloud/aws/packer/build_aws_ami.pkr.hcl"
